version: '3'

services:
  server:
    build: ./
    container_name: express
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
    tty: true
    stdin_open: true

  db:
    container_name: 'postgres'
    image: 'postgres:14.1-alpine'
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped

volumes:
  postgres_data:
